# Site settings
title: Zernerda Bot
description: Внушительный набор функционала для "пробива" информации и самая большая база данных.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zernerda Bot
user_description: Зернерда это бот для пробива данных с расширенным функционалом! В отличие от аналогов, Zernerda выгодно выделяется широким спектром возможностей. Бот обладает самой большой базой данных, собранной из различных утечек и взломов в сети. Вы можете проводить поиск не только по стандартным параметрам, таким как электронная почта, номер телефона, автомобили, адреса, полные имена и IP-адреса, но также и по Instagram, Facebook, Twitter.
user_title: Уникальные возможности в пробива!
# email: Zernerda@gmail.com
# twitter_username: lorem_ipsum
# instagram_username: Zernerda
# facebook_username: Zernerda
# linkedin_username: Zernerda
github_username:  ZernerdaBot
# medium_username: Zernerda
# medium_url: Zernerda
# gplus_username:  Zernerda

exclude: ['package.json', 'src', 'node_modules', 'vendor']

